import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/global.scss";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";
import DirectionProviderWrapper from "@/providers/DirectionProviderWrapper";
import SessionWrapper from "@/providers/SessionWrapper";
import ProviderWrapper from "@/providers/ProviderWrapper";
import { ToastContainer } from "react-toastify";
import Script from "next/script";

const arLight = localFont({
  src: "../assets/fonts/ARABIC-LIGHT.ttf",
  display: "swap",
  variable: "--font-ar-light",
});

const arMedium = localFont({
  src: "../assets/fonts/ARABIC-MEDIUM.ttf",
  display: "swap",
  variable: "--font-ar-medium",
});

const arBold = localFont({
  src: "../assets/fonts/ARABIC-BOLD.ttf",
  display: "swap",
  variable: "--font-ar-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={`${arLight.variable} ${arMedium.variable} ${arBold.variable}`}>
      <body className={`antialiased font-ar-medium`}>
        <ToastContainer />
        <ProviderWrapper>
          <SessionWrapper>{children}</SessionWrapper>
        </ProviderWrapper>
        <Script src="/nutrient-viewer/nutrient-viewer.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
